/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Knight({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Knight.glb')
  const { actions, mixer } = useAnimations(animations, group)
  
  return (
    <group ref={group} {...props} actions={actions} mixer={mixer} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, 0, 1.07]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Knight_Low" position={[0, 0.28, -0.25]} />
          <group name="Shield" position={[-1.61, -0.28, 0.98]} rotation={[1.16, 0.94, -0.6]} />
          <group name="Sword" position={[0.63, -0.96, 1.11]} rotation={[1.1, -0.75, -1.02]} />
          <primitive object={nodes.Armature_rootJoint} />
          <mesh>
            <mesh visible={false} position={[0,0,1.3]} rotation={[Math.PI*0.5,0,0]}>
            <capsuleBufferGeometry args={[1,1.3,5,10]} rotation={[0,0,Math.PI * 0.5]} />
            </mesh>
            <skinnedMesh name="Knight_Low_0" geometry={nodes.Knight_Low_0.geometry} material={materials.Armor} skeleton={nodes.Knight_Low_0.skeleton} />
            <skinnedMesh name="Knight_Low_1" geometry={nodes.Knight_Low_1.geometry} material={materials.Leather} skeleton={nodes.Knight_Low_1.skeleton} />
            <skinnedMesh name="Shield_0" geometry={nodes.Shield_0.geometry} material={materials.Shield} skeleton={nodes.Shield_0.skeleton} />
            <skinnedMesh name="Sword_0" geometry={nodes.Sword_0.geometry} material={materials.Sword} skeleton={nodes.Sword_0.skeleton} />
            <skinnedMesh name="Sword_1" geometry={nodes.Sword_1.geometry} material={materials.SwordLeather} skeleton={nodes.Sword_1.skeleton} />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Knight.glb')
